# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc69a7c21d3f2a132503b2ce164d75426c6cbaf3fd022b43fe80166048ba0115bf80f69fa31c75505ad6e09db78c9dffee73e7c89fe35721a295fd4361565028

test:
  secret_key_base: d3a4202a79af1a5c43e12230e508d9642a0b63560b833610fdca318823241f9b30cf3990a0dce4b4ee525f15eb7ee43ae0989cc2e213f14aa8d73450c7e88431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
